"""init

Revision ID: 9bb96ab0002b
Revises: d5fa329f1670
Create Date: 2025-10-05 17:33:15.024479

"""
from alembic import op
import sqlalchemy as sa
import sqlmodel.sql.sqltypes
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision = '9bb96ab0002b'
down_revision = 'd5fa329f1670'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('userfilter',
    sa.Column('user_id', sa.Integer(), nullable=False),
    sa.Column('category', postgresql.ARRAY(sa.UUID()), nullable=True),
    sa.Column('source', postgresql.ARRAY(sa.UUID()), nullable=True),
    sa.Column('search', sqlmodel.sql.sqltypes.AutoString(length=500), nullable=True),
    sa.Column('start_date', sa.DateTime(), nullable=True),
    sa.Column('end_date', sa.DateTime(), nullable=True),
    sa.Column('sort', sqlmodel.sql.sqltypes.AutoString(length=10), nullable=True),
    sa.PrimaryKeyConstraint('user_id')
    )
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('userfilter')
    # ### end Alembic commands ###
