"""initial_models

Revision ID: aebcdad97376
Revises: 
Create Date: 2025-10-06 17:44:18.398332

"""

from alembic import op
import sqlalchemy as sa
import sqlmodel.sql.sqltypes
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision = 'aebcdad97376'
down_revision = None
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('category',
    sa.Column('id', sa.Uuid(), nullable=False),
    sa.Column('name', sqlmodel.sql.sqltypes.AutoString(length=100), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_category_name'), 'category', ['name'], unique=True)
    op.create_table('source',
    sa.Column('id', sa.Uuid(), nullable=False),
    sa.Column('name', sqlmodel.sql.sqltypes.AutoString(length=255), nullable=False),
    sa.Column('domain', sqlmodel.sql.sqltypes.AutoString(length=255), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_source_name'), 'source', ['name'], unique=True)
    op.create_table('userfilter',
    sa.Column('user_id', sa.BigInteger(), nullable=False),
    sa.Column('category', postgresql.ARRAY(sa.UUID()), nullable=True),
    sa.Column('source', postgresql.ARRAY(sa.UUID()), nullable=True),
    sa.Column('search', sqlmodel.sql.sqltypes.AutoString(length=500), nullable=True),
    sa.Column('start_date', sa.DateTime(), nullable=True),
    sa.Column('end_date', sa.DateTime(), nullable=True),
    sa.Column('sort', sqlmodel.sql.sqltypes.AutoString(length=10), nullable=True),
    sa.PrimaryKeyConstraint('user_id')
    )
    op.create_table('processednews',
    sa.Column('id', sa.Uuid(), nullable=False),
    sa.Column('title', sqlmodel.sql.sqltypes.AutoString(length=500), nullable=False),
    sa.Column('summary', sa.Text(), nullable=False),
    sa.Column('url', sqlmodel.sql.sqltypes.AutoString(length=500), nullable=False),
    sa.Column('published_at', sa.DateTime(), nullable=False),
    sa.Column('source_id', sa.Uuid(), nullable=False),
    sa.Column('category_id', sa.Uuid(), nullable=False),
    sa.ForeignKeyConstraint(['category_id'], ['category.id'], ),
    sa.ForeignKeyConstraint(['source_id'], ['source.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_processednews_published_at'), 'processednews', ['published_at'], unique=False)
    op.create_index(op.f('ix_processednews_title'), 'processednews', ['title'], unique=False)
    op.create_table('newsvector',
    sa.Column('id', sa.Uuid(), nullable=False),
    sa.Column('news_id', sa.Uuid(), nullable=False),
    sa.Column('vector', sa.JSON(), nullable=True),
    sa.ForeignKeyConstraint(['news_id'], ['processednews.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_newsvector_news_id'), 'newsvector', ['news_id'], unique=True)
    op.create_table('userhistory',
    sa.Column('id', sa.Uuid(), nullable=False),
    sa.Column('user_id', sa.BigInteger(), nullable=False),
    sa.Column('news_id', sa.Uuid(), nullable=False),
    sa.Column('view_timestamp', sa.DateTime(), nullable=False),
    sa.ForeignKeyConstraint(['news_id'], ['processednews.id'], ),
    sa.ForeignKeyConstraint(['user_id'], ['userfilter.user_id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_userhistory_view_timestamp'), 'userhistory', ['view_timestamp'], unique=False)
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_userhistory_view_timestamp'), table_name='userhistory')
    op.drop_table('userhistory')
    op.drop_index(op.f('ix_newsvector_news_id'), table_name='newsvector')
    op.drop_table('newsvector')
    op.drop_index(op.f('ix_processednews_title'), table_name='processednews')
    op.drop_index(op.f('ix_processednews_published_at'), table_name='processednews')
    op.drop_table('processednews')
    op.drop_table('userfilter')
    op.drop_index(op.f('ix_source_name'), table_name='source')
    op.drop_table('source')
    op.drop_index(op.f('ix_category_name'), table_name='category')
    op.drop_table('category')
    # ### end Alembic commands ###
